---
name: CI
on: [push]

jobs:

  test:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - centos8
          - debian10

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up python3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test deps.
        run: pip3 install molecule molecule-docker docker yamllint ansible-lint

      - name: Run molecule tests.
        run: molecule test
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
